# Change these first
owner: TFPJobs # Your GitHub organization or username, where this repository lives
repo: ex_status_page # The name of this repository

sites:
  - name: Exchange User Portal 
    url: https://bwex-user-prod.vercel.app/
  - name: Exchange User Portal QA
    url: https://bwex-user-qa.vercel.app/
  - name: Exchange Admin Portal
    url: https://bwex-admin-prod.vercel.app/
  - name: Exchange Admin Portal QA
    url: https://bwex-admin-qa.vercel.app/
  - name: Exchange API
    url: https://exchange1.bitwage.com/
  - name: Exchange API QA
    url: https://exchange2.bitwage.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /ex_status_page
  name: Ex Status Page
  introTitle: "Ex Status Page"
  introMessage: This monitors using upptime
  
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
